### ISSUE TITLE
Song select search OR gate, brackets, exclude from search, and search presets

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1097]
The following would be useful additions to the in-game song search:

- An OR logic gate, as currently if there are multiple search terms then the results must match all of the terms (as if there's an AND between each search term). Can be assigned "||" like in code because using the word "or" might lead to confusion when someone searches for the word "or".
Example search: bpm>240 || diff>30 (must be over 240 bpm OR over 30 diff)

- Brackets for more advanced OR and AND search operations.
Example search: (k=4 d>25 d<35 ln<20%) || (k=7 d>8 d<15)

- Search exclusions, when a word is prefixed with a certain character, such as "-", then it shows all the results that don't have that word.
Example search: status=r -Sotarks (shows all ranked maps excluding anything with Sotarks)

- Search presets, being able to save oddly specific and long search phrases somewhere for quick access so that you don't have to type the entire search phrase every time.

**Comment by IceDynamix** [comment]
Search Exclusion by a hyphen might cause problems with usernames that contain a hyphen at the front. Is there a list of disallowed characters in Quaver usernames? 

Maybe, instead of developing a better inline search filter system, we could implement something like Flash Flash Revolution has? A custom UI for complicated filters, all mix and matchable with ANDs, ORs, NOTs and whatnot. Might as well add presets at that point.

https://ffr.fandom.com/wiki/FAQ#How_do_I_find_songs_of_a_certain_difficulty_level_or_range.3F

https://vignette.wikia.nocookie.net/ffr/images/6/64/Difficultyfilter.png/revision/latest?cb=20180419034352

**Comment by robby250** [comment]
Could also implement ` as an escape character for when you don't want to exclude a word and instead search for something that starts with "-". UI is better for noobs but when you know how to search simply typing is much easier.
