### ISSUE TITLE
Map preview should indicate more clearly that you can playtest

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1540]
Instead of "Press [TAB] to toggle autoplay" that fades out (and it can fade out before you open preview map which means it's never shown) it should show something like "Press [TAB] to try playing the map right here" or something and should be visible at all times.

**Comment by robby250** [comment]
It would be annoying to see constantly. Currently it shows up for a few seconds every time you enter song select and pop up the preview. I think it's fine as it is, but if it's not enough then the text could pop up for 1 second every time you switch map with preview on, or every time you toggle preview. Even that would be too much because the user has to be informed just once in order to know about it.

Instead of changing it at all I think it could be mentioned in a panel that shows info about all the hotkeys that you can use in song select.
