### ISSUE TITLE
Editor: LNs shorter than their actual size in the beginning of test play

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#1872]
**Describe the bug**
At least in 7K I'm observing a bug where LNs close to the start of the test play appear shorter in test play than they actually are. When you're holding them they jump to their normal length as you hold them sometimes and sometimes their top is just missing.

**Comment by Hey-S1r1** [comment]
Here is a writeup of the issue:

Describe the bug:
At certain configurations of scroll velocities, when shorter long notes are in close proximity to each other, they appear fine in the map preview, but not in actual gameplay. This applies both in the editor (Display Gameplay Preview vs Test Play) and out of the editor (View Map vs Play).
In the attached video, I display what happens to shorter long notes in close proximity at scroll velocities ranging from 1.00 to 1.60 at intervals of 0.05. None of the long notes show when the scroll velocity is 1.10 or below. The most problematic velocity is 1.15. Velocities from 1.20 to 1.40 (inclusive) all have an identical result that is not expected. Velocity 1.45 has an unexpected result slightly different from 1.20 to 1.40. Velocities 1.50 and above do not have issues as far as I can tell.

To Reproduce
Steps to reproduce the behavior:
1. Go to the editor.
2. Turn on Display Gameplay Preview. Place shorter long notes in close proximity to each other. Be sure to adjust the scroll velocity just enough that the shorter long notes start appearing in test play.
3. Test play the section with said shorter long notes.
4. See error.
5. Save map and see view map outside of editor (there should be no error here).
6. Play map outside of editor.
7. See error.

Expected behavior:
Preview of shorter long notes should match the gameplay.

Desktop (please complete the following information):
* OS: Windows 11
* Browser(?): Steam
* Version 1.1.2 Full Release

Additional context
This issue occurs twice in my unranked map Desire Blue Sky. The BPM of the song is 143 if it matters.
Link to bug video: https://drive.google.com/file/d/1awtUmCdg9-t-h-qQzfGN_Try6TyvUYX4/view?usp=sharing

**Comment by Hey-S1r1** [comment]
Also to be noted: while pressing the restart button does somewhat change the LN calculation, it does not fully fix it.
