### ISSUE TITLE
Editor: Actions in a plugin window also affect the editor

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2104]
Mouse wheel scrolling in a plugin imgui window causes the editor to scroll, while built in editor tools do not.

Dragging a plugin window cause a selection to be made.

Composition tools can be switched while focused on a plugin window.

Default editor panels(?), such as the details, composition tools, layers, and hitsounds panels, are able to be dragged with a plugin window.

**Comment by IceDynamix** [comment]
A plugin state variable has been created for this, which prevents user interaction with the editor while hovered over a plugin window. Add following line to your code:

 ```lua
state.IsWindowHovered = imgui.IsWindowHovered()
```

**Comment by Illuminati-CRAZ** [comment]
Would there be any problems if the game by default implemented this?

**Comment by Swan** [comment]
Some plugins may want to keep editor functionality even though the mouse is hovered over it (ex. some type of overlay or visualizer)

**Comment by YaLTeR** [comment]
I'm not sure I understand this correctly, but wouldn't it make more sense for plugin windows to behave like the editor windows by default, with an opt-in for the overlay use-case?

**Comment by Swan** [comment]
Probably, but there's also a technical limitation as well. Plugins can have an unlimited amount of windows, and `ImGui.IsWindowHovered()` needs to be called to handle each individual one. 

This also needs to be called before `ImGui.End()` in order to track hovering for that specific window. It's just much easier for the author to handle it themself in the script.
