### ISSUE TITLE
No audio on Linux

### ISSUE THREAD

**Issue by 0chroma** [Quaver/Quaver#2274]
**Describe the bug**
Audio doesn't play. Chart doesn't scroll in single player and song is stuck at 0:00 in jukebox

**To Reproduce**
1. Start Game
2. Go to anything where sound should output (jukebox, single player)

**Expected behavior**
The audio plays, chart scrolls

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 0.19.1

**Additional context**
It looks like quaver is connecting to pulseaudio via the ALSA plugin, not directly. Tried both runtime + native versions of steam and it's the same result

**Comment by YaLTeR** [comment]
> It looks like quaver is connecting to pulseaudio via the ALSA plugin, not directly.

Yes, that's normal, Bass (the audio library we're using) has never got a native PA backend.

This means that you need to set up pulseaudio-alsa correctly: https://wiki.archlinux.org/index.php/PulseAudio#ALSA

**Comment by 0chroma** [comment]
oh I have it set up properly, other alsa-only things like `aplay` work without issue.

**Comment by YaLTeR** [comment]
Not sure what's the cause then. Quaver definitely should work on Arch.

**Comment by 0chroma** [comment]
I can provide logs or troubleshoot if that'd be helpful, just not sure how to collect them

**Comment by Duder963** [comment]
I'm also experiencing this problem. At first I thought it was a problem with my JACK setup but even disabling JACK no audio plays.

**Comment by YaLTeR** [comment]
Not sure what that could be caused by; everywhere I tested (Arch with PA, Fedora, Ubuntu, Mint) everything worked fine.

**Comment by OtterGauze** [comment]
I can't reproduce this, I've tried on relatively barebones Arch, Fedora and Pop!_OS / Ubuntu 20.04 - It might be worth checking for the unlikely scenario that maybe Quaver is outputting to the wrong device accidentally (if you have any others, that is)

**Comment by 0chroma** [comment]
I checked that, it's def outputting to the right sound device but it just looks like pulse isn't getting any output to it

again if there's anything I can do to help debug I'm more than happy to, just not sure what would be useful

**Comment by Luminiscental** [comment]
I had this issue as well on arch linux with pulseaudio, but managed to fix it with a combination of 

- installing pulseaudio-alsa 
- installing lib32-libpulse and lib32-alsa-plugins for steam as per the wiki-page that mentions pulseaudio-alsa 
- making sure to remove conflicting defauls in /etc/asound.conf that override the settings from pulseaudio-alsa (looking at some outdated wiki information it seems the package used to use /etc/asound.conf but now it just adds a file to /etc/alsa/conf.d)

I think prior to going through these my alsa setup was slightly broken, I didn't think to check aplay, but maybe the multilib packages could be OP's issue? the relevant bit in the [wiki](https://wiki.archlinux.org/index.php/PulseAudio#ALSA) says 

> Also install lib32-libpulse and lib32-alsa-plugins if you run a x86_64 system and want to have sound for 32-bit multilib programs like Wine and Steam. 

although I'm not sure if this applies to Quaver itself rather than just Steam

**Comment by YaLTeR** [comment]
Might be a good idea to add this to the wiki faq?

**Comment by 0chroma** [comment]
got it working after deleting a stray ~/.asoundrc file that ended up causing the issue, sorry about that!

**Comment by Duder963** [comment]
@0chroma that proved to be the problem, both with Quaver and with a similar problem with Clone Hero
