### ISSUE TITLE
Implement Negative SV

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#249]
Allow SV to be a negative value.

Precautions:
- Implement reverse direction LN
- Flip LN tail on reverse
- Might require changes on Quaver.API (when importing maps/validating maps)

**Comment by Swan** [comment]
The only issue that I've seen is that LNs [don't actually appear with negative SV](https://streamable.com/pub10) because the height is most likely a negative value, but it can be easily solved by using the absolute value of whatever length it is. 

Negative BPM also isn't necessary, so I've renamed the issue.

**Comment by YaLTeR** [comment]
Actually, additional handling is needed for the case where SV changes back and forth during a held LN. I do have ideas on how to implement that properly.
