### ISSUE TITLE
No audio (Arch Linux)

### ISSUE THREAD

**Issue by Sorcerer17** [Quaver/Quaver#2578]
**Describe the bug**
While playing the game there is no audio whatsoever

**To Reproduce**
1. Open the game

**Expected behavior**
You can interact with the menus but there is no audio. Levels do not play.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Linux Kernel: 5.8.1-arch1-1

**Comment by YaLTeR** [comment]
So far 100% of Linux audio issues were caused by system misconfiguration.

Assuming you're using PulseAudio,
1. Set up pulseaudio-alsa: https://wiki.archlinux.org/index.php/PulseAudio#ALSA
1. Check that you don't have `~/.asoundrc` with custom settings.
1. Check that you don't have `/etc/asound.conf` with custom settings.
1. Check that you don't have configs in `/etc/alsa/conf.d/` that break pulseaudio-alsa.
1. Check other ALSA config locations (I don't know which other ones there are, it could vary per distribution).
1. Make sure `aplay` can play back audio files without any extra configuration (using the default device).

**Comment by YaLTeR** [comment]
@Sorcerer17 did those steps help you solve the issue?
