### ISSUE TITLE
Note Misses

### ISSUE THREAD

**Issue by fint54321** [Quaver/Quaver#2598]
**Is your feature request related to a problem? Please describe.**
One thing I have always found a bit bothersome in these kinds of rhythm games is what's considered a miss and what isn't. The problem is with accidental key presses. If you press a key even when there isn't a note nearby, there is no penalty. This makes sense if there are no notes on screen whatsoever, or if the notes are still far away from the receptors, but there are many cases where it is just too lenient. 
For example, if there's a pattern with alternating fingers but you get tangled up and hit one of the keys with the wrong hand, that should be considered a miss. You've made a blatant error. Your brain misread the screen and mistakenly tried hitting a note that wasn't there.

**Describe the solution you'd like**
Unless there are no notes near the receptors, any key presses that don't hit a note should be counted as misses.

**Comment by IceDynamix** [comment]
The window of when an early hit counts as a miss is 164ms as defined by the Standard judgement window. If you are having trouble with the window being too lenient, then you're free to create your own judgement windows in the Mods panel.

> For example, if there's a pattern with alternating fingers but you get tangled up and hit one of the keys with the wrong hand, that should be considered a miss. You've made a blatant error. Your brain misread the screen and mistakenly tried hitting a note that wasn't there.

If you try to hit a note that wasn't there for a note in another column that was there, then it means that you're not hitting the intended note, which results in a miss. If you were to imagine that scenario in a denser map, then hitting a note in a column you didn't intend in will most likely already count as either a Good, Bad or Miss, since you're hitting it either early or late.

Calculating misses right now (164ms window for each note in each column) is controlled and very easy to understand, changing that behavior to cover multiple columns could be detrimental to techniques such as manipulating (which is widely considered a valid skill).

Even if the miss behavior were to be adjusted, it would require a recalculation of all current scores which is something that has only been done for accuracy weight adjustments (does not require full analysis of the replay) or would be considered in the future for difficulty calculator adjustments (does not require full analysis of the replay). Recalculating all scores for the new miss behavior (requires full analysis of the replay) for a change only a minority of the community could get behind is not worth it in my opinion.
