### ISSUE TITLE
No Miss Modifier Ranked?

### ISSUE THREAD

**Issue by fint54321** [Quaver/Quaver#2603]
**Is your feature request related to a problem? Please describe.**
I don't think it makes much sense for the no miss mod to automatically disable ranked results. The main reason people use it is so that they can practice difficult maps above their skill level, or just because they enjoy playing and don't care too much if they mess up; they just want to finish the map regardless. Obviously, if you lose all of your health, you shouldn't qualify for ranked results, but if you have no miss on and you _don't_ lose all your health, then what difference does it make?

**Describe the solution you'd like**
Have the no miss mod not set you to unranked unless you actually drop to zero health during gameplay.

**Comment by Razorflamekun** [comment]
I'm 100% positive that this won't be changed.  By no miss, I am assuming you mean the No Fail mod.  In this instance, the reason why the No Fail mod is not ranked is because if you have to use it in the first place, the file is probably too hard for you to play for ranked score.  As you yourself have stated, it is good for _practice_ and in my mind, practice does not equal ranked.
