### ISSUE TITLE
Save scores for unranked/imported maps

### ISSUE THREAD

**Issue by trevorfirl** [Quaver/Quaver#2643]
I have a bunch of imported maps, however can not see which ones I have played and which I have not. I wish to be able to see the scores I have received locally on my imported/unranked maps.

**Comment by Razorflamekun** [comment]
If you are a donator, all scores are saved for every map, even if they are listed from other games.  If you are not a donator, I am 100% positive that your scores will still be saved in the Local scores leaderboard for that song, however, it will not show a letter grade unless you have the donator status because that is the only status that allows you to get scores saved to the global leaderboards.
