### ISSUE TITLE
No success trying to build & run on Linux

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#270]
I hit several issues trying to build and run Quaver on Linux, some of which I could fix, but not all of them. I am running Arch Linux x64 with dotnet 2.2.100.

I cloned the repository with submodules and proceeded with `dotnet restore`, which worked fine, except for three (possibly related) warnings:
```
/home/yalter/Source/cs/Quaver/Wobble/Wobble/Wobble.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
/home/yalter/Source/cs/Quaver/Quaver/Quaver.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
/home/yalter/Source/cs/Quaver/Quaver.Shared/Quaver.Shared.csproj : warning NU1701: Package 'MonoGame.Extended 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/yalter/Source/cs/Quaver/Quaver.sln]
```

Then I ran `dotnet msbuild /property:Configuration=Release` which also completed fine.

Finally, I tried to `dotnet bin/Release/netcoreapp2.1/Quaver.dll` to be hit with the first issue:
https://github.com/Quaver/Quaver/blob/c280702fce80456c7b9be68c0b870aa4fc5dbb34/Quaver/Program.cs#L24
This third `/` in the `file:///` pattern actually cuts off the first character of a Linux absolute path which makes it a relative path instead and breaks everything. Replacing the pattern with `file://` allowed me to progress through this step.

Next, `dotnet bin/Release/netcoreapp2.1/Quaver.dll` told me it couldn't load the Steam API and indeed, the repository seems to only contain the Windows `steam_api64.dll`. I went ahead and downloaded the Steamworks SDK, extracted `libsteam_api.so` out of there and placed it as `libsteam_api64.so` into the output directory along with `Quaver.dll`.

Now running the game seems to not produce any errors, but instead of actually launching the game it tries to download some unrelated 1 MB large game from Steam ("Spacewar"). I have no idea why or how to fix that. Downloading that from Steam and trying to run Quaver again makes it try running that "Spacewar" game.

**Comment by YaLTeR** [comment]
I see. Well, I'll be glad to help test (and possibly fix) stuff on Linux when that works. I missed the key giveaway but if I understand correctly it should be possible to build Quaver and play offline without Steam.

**Comment by YaLTeR** [comment]
Update: in Debug mode it doesn't try downloading a Steam game, just outputs
```
[7:53:22] - RUNTIME - IMPORTANT: Config file has been successfully read.
```
and doesn't seem to do anything else past here (doesn't quit either).

**Comment by Swan** [comment]
Linux and OSX are going to be a bit of a challenge. 

**Addressing the first issue:**

https://github.com/Quaver/Quaver/blob/c280702fce80456c7b9be68c0b870aa4fc5dbb34/Quaver/Program.cs#L24

This was put into place so that the application knows where to find necessary dlls - specifically `bass` when doing some testing a few months ago.

We'll need to find a proper way to load native dlls. The first step would be to open an issue in [Wobble](https://github.com/Quaver/Wobble), as everything related to audio is handled there.

**Second Issue - Steam & .NET Standard**

Currently Quaver uses Steamworks.NET, and the dll included is windows specific. We'll need to grab the linux/osx versions of the Steam API dll and place them accordingly. 

Steamworks.NET also uses .NET Framework which we need to avoid doing, and we should be using .NET Standard libraries going forward for guaranteed cross-platform compatibility. We should be looking for another wrapper library to replace Steamworks.NET (or convert to .NET Standard) and all other leftover .NET Framework dependencies we have.
