### ISSUE TITLE
Rankings at result screen not working properly.

### ISSUE THREAD

**Issue by JaanJah** [Quaver/Quaver#276]
**Describe the bug**
After submitting your play. The result screen shows Map rank, global ranking and country ranking.
Map rank always shows N/A for me. Global ranking is correct, but country ranking shows the exact same number as global ranking. even though I am the only Estonian player in my country.

**To Reproduce**
1. Pick a map
2. Play the map until the end
3. After finishing your play wait for the score to submit

**Expected behavior**
Show correct map ranking and country ranking

**Screenshots**
https://i.imgur.com/OLdxoHg.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Map I was playing on was Rabbit House - Have a Party Time! [neyoru's 4K Insane]

**Comment by Sublimity** [comment]
#277 The country value was probably set as a placeholder due to it possibly not being implemented yet on the back-end API, same goes for the map rank, n/a is what it'll default to if it fails to retrieve your map rank from the submission results.

Either way, I still changed the placeholder country value to the correct value, on the dev builds it won't be visible anyways, and if it gets chucked into the master branch the back-end code will probably be implemented already.
