### ISSUE TITLE
Game crashed immediately after joining a multiplayer lobby

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2885]
https://quavergame.com/multiplayer/game/65119

[network.log](https://github.com/Quaver/Quaver/files/6113603/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/6113604/runtime.log)

**Comment by Illuminati-CRAZ** [comment]
tried again and joined with low fps, then tried downloading the map and crashed

[network.log](https://github.com/Quaver/Quaver/files/6113615/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/6113616/runtime.log)

**Comment by QiuFeng54321** [comment]
ditto
I'm suffering it rn

**Comment by ARXChrono** [comment]
Why is this closed? I don't see one that is opened still...

This still happens for me as well, crashes immediately after joining a multiplayer lobby.

**Comment by Galexion** [comment]
Ok Seriously, this bug needs to be fixed because people are obviously experiencing it, including me. The game legit says to bring up issues here yet this one isnt getting fixed?

why?

**Comment by Swan** [comment]
@Galexion Because it is a free and open source project, and we work on it in our spare time. If you haven't noticed, there's 400+ other open issues that we are tackling. You have access to the code the same way that we do. If you have an issue, and you want it fixed now, you can kindly do it yourself or wait. You aren't entitled to a damn thing, so don't make comments like this as if we owe you something.
