### ISSUE TITLE
Add Feature Introduction Tabs For new Players

### ISSUE THREAD

**Issue by ravindurra** [Quaver/Quaver#2951]
When I started the game as a new player, there is no instructions or definitions for what each feature mean. It is frustrating that a new player has to figure out these features by himself by either playing the game blindly or looking at the internet gaming websites or videos. It is time-consuming and can drive away new potential players.

**Comment by QiuFeng54321** [comment]
I think this feature is needed especially in multiplayer games, where new players get a pop up tutorial box showing what each button does in a lobby. New players don't know how to download the map, what the crown represents and what the "ready" button does differently when they are a player and a host so they just mindlessly click the button even when they are host so the game just starts again. The most time of restart of game caused by misusing of the ready button I've ever experienced is like 4 times which is really disturbing to everyone in the lobby.
