### ISSUE TITLE
Steam Workshop / Skins problems

### ISSUE THREAD

**Issue by O2Joni** [Quaver/Quaver#3087]
**Describe the bug**
The bug is simple, when i try to download a skin the skin doens't apears on Quaver, so i verify the integration of files on Quaver and starts to download steam content, but when i opened the game the skins are distingued by numbers intead the original name.

**To Reproduce**
X
**Expected behavior**
After the verification on files i expected to work beacause it started to download steam workshop content.

**Screenshots**
X

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 20H2

**Additional context**
X

**Comment by chirijidev** [comment]
That's because the author didn't make the skin name in skin.ini the same as the workshop item title. The numbers are basically the Steam ID of the skins since they're a workshop item.

Also they'll appear once Steam's done downloading them. Usually, you just go to the Main Menu and check Settings there. Then you'll see the skins you've subbed to appear in the skin settings.
