### ISSUE TITLE
[QOL] Editor key recording to map (great name)

### ISSUE THREAD

**Issue by FIshJuiceS** [Quaver/Quaver#3228]
Making and editing custom quaver maps can be tedious at times.

I suggest a new system that can record your key presses and translate them onto a quaver map.

Alternatives to this would be a new map format/ .qp reading and editing application for easy and simplistic map creation

A system to record keypresses (of ASKL or whatever your keybindings are) with the time they are pressed (and note length for hold notes) and then some way to convert something like `A 0:05 2` into a hold note of `A` or the left most key for 2 seconds when you are 5 seconds into the song.

I can try follow up and elaborate on this if needed and sorry if the idea is a little ambitious or *stupid*

**Comment by IceDynamix** [comment]
there's already a way to "livemap" by using the number row to place notes during playback, it snaps to the timing correctly but does not support long notes

**Comment by IceDynamix** [comment]
> Alternatives to this would be a new map format/ .qp reading and editing application for easy and simplistic map creation

the quaver editor is already easy to use and one of the best ways to edit vsrg files as of now, the only complex thing is timing but that's something you'll have to do in every editor so there's no way around it

use this tutorial available on the quaver wiki if you're confused https://wiki.quavergame.com/docs/Editor/Getting_started

**Comment by IceDynamix** [comment]
finally, trying to livemap will result in a map of very poor quality, which is why, assuming you were to submit a livemapped map to the ranking queue, it would almost instantly get denied or maybe even blacklisted.

they're also not fun to play and to make and very hard to make good unless you're an insanely good player and mapper who can visualize all patterns exactly as they want and play them correctly.
