### ISSUE TITLE
Can't upload mapset

### ISSUE THREAD

**Issue by wv11** [Quaver/Quaver#3334]
I don't think this is a bug but whenever I try uploading my mapset it says "Your mapset contains files of an invalid type". I have no idea what files could possibly be invalid. My audio file is an mp3 and my background image is a png. I tried using a jpg for the background as well but it still didn't work. I don't know what I'm doing wrong and I just want to be able to upload my mapset.

**Comment by IceDynamix** [comment]
sometimes your mp3 is actually something different, especially when downloading from a converter site. if you know how to use ffmpeg, try to pass it through that without any arguments and it should clean up the file. otherwise, try to download a clean version of the song or check whether someone already mapped the song and you can take the mp3 from there.
