### ISSUE TITLE
"Impossible" incorrectly converts scores to "standard*"

### ISSUE THREAD

**Issue by blubberblub149** [Quaver/Quaver#3410]
Pretty much as the tile says. Playing a map on impossible timing windows will sometimes convert the hits and misses incorrectly causing 1 miss to become 7 for example.

1. Set timing windows to impossible
2. Play a tough chordjack map (it is most prominent on them)(the one's i've experienced it on is "Takami o mezashite" and "I feel it coming")
3. Play a portion of the map or the whole thing
4. Convert score at the end and see how it increases the misses despite the timing windows becoming more lenient

The misses should stay the same or decrease, I cannot tell if the added misses are affecting my ranked accuracy or not

![2272022 16-46-3-590](https://user-images.githubusercontent.com/100529516/155891709-3579801f-7b42-41e0-ab45-a75cdfaae7f2.jpg)
![2272022 16-46-8-110](https://user-images.githubusercontent.com/100529516/155891710-4e76c89f-e026-4099-b955-f1026c54170b.jpg)

**Comment by Jolomann** [comment]
sadly this isn't fixable because changing the miss window is the direct cause of this. you can't see the misses while playing because the miss window has changed, but on standard they would be misses. not a bug, just funny judgement window interaction

you can work around the issue if you make your own judgement windows and leave the outer windows (good, okay, miss) as default, and only change marv, perf, and great. this way you won't get nasty surprises when converting

**Comment by blubberblub149** [comment]
ok thanks, now that i think about it I can see the issue. Yeah, I'll make custom timing windows. I wasn't too sure if it was a bug or not but I thought I'd post it here regardless to make sure
