### ISSUE TITLE
Game is low res even though set to 1080p

### ISSUE THREAD

**Issue by Debeselis420** [Quaver/Quaver#3411]
**Describe the bug**
Game sets a low default resolution, changing it feels like it only upscales it, even Nvidia's performance overlay is low res

**To Reproduce**
It seems like it only happens to be, not my friends, but
1. Launch game
2. Change 1366x768 to 1920x1080
3. Done

**Expected behavior**
Not blurry

**Screenshots**
https://imgur.com/a/CYRelEY

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Firefox
 - Version 0.31.0

Notes : 
My monitor is 1080p, scaling in windows is set to 100% too, tried reinstalling / deleting and editing the .cfg file

**Comment by makaiiart** [comment]
I don't think Nvidia's performance overlay has to do with anything game related.

Some boxes with rounded corners mostly just look weird because it's a square-ish rounded texture being stretched instead of being divided into 6, using masks for corners or draw rounded rectangles directly. 
Here's an example in an image editor showing the effective difference:
![Designer_XQvcjz9xtw](https://user-images.githubusercontent.com/53101675/156515699-cf7cd044-0111-4e4b-bfe8-652d35f7b7d1.gif)

Other things may look lower res due to a lack of texture filtering and/or mipmapping. Some elements based on 768p, but with the texture for 1080p and also make the default interpolation the game currently uses to go nuts and degrade them when rendered. Notably anything rounded or with angled edges.

So my conclusion, at least from looking at your screenshots, is that your Quaver looks perfectly normal and your friends just aren't picking up on these lack of polish.
