### ISSUE TITLE
Game Freezes everytime I place a note in the chart editor (Windows 10)

### ISSUE THREAD

**Issue by fishfries** [Quaver/Quaver#3566]
Describe the bug
Everytime I place a note in the chart editor it laggs, eventhough I get arround 120 while playing. I've tried changing resolution, optimization, closing all my application in the background, changing the fps limiter. This is happening recently, but before this was happening it was working perfectly fine and I had average fps.

Desktop (please complete the following information):

OS: Windows
Browser Google
Version 10

Run time log: [runtime.log](https://github.com/Quaver/Quaver/files/9125831/runtime.log)

**Comment by AiAe** [comment]
What are your PC specs? 
Is the song you trying to map long?
Does it have a lot of notes?

**Comment by CornerPin** [comment]
Had the same issue, it turned out there was a note with the `StartTime` property set to `-2147483648`. Manually removing it from the `HitObjects` section of the `.qua` file fixed the FPS drops.
![image](https://user-images.githubusercontent.com/7669876/179855828-b8990a5c-2041-4862-a285-a4311f6a0fdd.png)
Make sure to make a copy of the file before editing it with a text editor, just in case.
