### ISSUE TITLE
Black screen when applying modifiers to both osu! and stepmania imported songs

### ISSUE THREAD

**Issue by Abriel14** [Quaver/Quaver#358]
**To Reproduce**
1. Download [this map for example](https://osu.ppy.sh/beatmapsets/661022#mania/1399542) and import it to the game
2. Add a 1.1 modifier
3. Start the music

Here is the log
[runtime.log](https://github.com/Quaver/Quaver/files/2707115/runtime.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/20484549/50397914-d05e8680-0773-11e9-89a0-3818e6e99dc6.png)

**Desktop (please complete the following information):**
 - OS: W10

**Comment by Sublimity** [comment]
This is a known bug, it isn't any rendering issues, it is just a general problem with modifiers causing the game to crash due to an object being null.

This has been fixed however in #348, so updating to the latest build of the **develop** upstream branch would be ideal.

You can close this issue now, thanks!

**Comment by Abriel14** [comment]
Okay sorry for disturbing
