### ISSUE TITLE
Significant FPS drops on heavy SV maps

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#3658]
**Describe the bug**
After the switch to .NET 6, the framerate tends to drop as gameplay goes on. Oftentimes for me, the framerate will drop to unplayable levels (like <20 fps), but will fix itself near the end of the map. Perhaps something to do with the hitobject pool?

**To Reproduce**
1. Go to song select and open gameplay preview.
2. Select a map with heavy SVs, such as https://quavergame.com/mapset/map/78585
3. Go to the middle of the map and observe the framerate dropping.

**Additional context**
Reproduced by Aiae on https://quavergame.com/mapset/map/92124

**Comment by Illuminati-CRAZ** [comment]
Just tried it out with a build compiled with the release configuration, and this issue didn't come up, so I guess this only happens with debug.

**Comment by Swan** [comment]
> Just tried it out with a build compiled with the release configuration, and this issue didn't come up, so I guess this only happens with debug.

Usually building with release decreases performance and caused a lot of stutters for the majority of players, which is why we have a special `Public` release config. Maybe something changed with net6.0 that fixes this.

It'd also be good to know why this issue happens when building with Debug by profiling the game.
