### ISSUE TITLE
Have a tick where audio offset applies to effect volume

### ISSUE THREAD

**Issue by Critseya** [Quaver/Quaver#3736]
**Is your feature request related to a problem? Please describe.**
At the moment, whenever I set my offset to -180ms to play with bluetooth headset, the effect volume which is pretty mandatory stays at 0ms offset

**Describe the solution you'd like**
I'd like a tick that makes the Audio offset sync the effect volume too.

**Describe alternatives you've considered**
I guess I can play without effect volume, but it just makes the game quite harder.

**Comment by YaLTeR** [comment]
The hitsounds play as soon as possible on hit. It's not physically possible to play hitsounds earlier because we don't know when the player will press the button. I suggest playing without hitsounds, especially in high latency situations.

**Comment by IceDynamix** [comment]
Handling offset with hitsounds is a difficult topic, especially with a large audio offset like this.

Using a bluetooth audio device results in the audio arriving late, hence a negative global offset is used to play the song audio earlier. Now the audio lines up with the visuals and your keytaps, but you still technically press 180ms later than you should.

Hitsounds play exactly when you tap, so they also play late by the same amount that you do. For hitsounds to stay accurate to the audio, they would also need to be played earlier. *But that's impossible by definition, since you would need to see 180ms into the future to see when the user is going to tap.*

The only solution to this would be to disregard user inputs and just play hitsounds like a type of metronome. But that's a topic for another day.

Playing without hitsounds is actually how most high-level players play the game, they concentrate on their own keytaps instead. It's across any rhythm game and builds cleaner technique in the long run.
