### ISSUE TITLE
AutoDeafen on discord

### ISSUE THREAD

**Issue by dannws** [Quaver/Quaver#4308]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I get to a certain point in a map while I'm in a VC in discord and my friends make noise which put me out of focus and can cause me to make mistakes.

### Describe the solution you'd like

Basically a feature in settings that allows you to set it where it automatically deafens once you reach a certain point in a map.

### Describe alternatives you've considered

I've setup a key bind to automatically deafen in discord but it is not really efficient since when I'm reaching the finishing of a map I rather pay all my attention on the map itself rather than on to press the key.

### Additional context

I've come to this idea originally from megahack, a popular mod on another rhythm game called geometry dash.

**Comment by AiAe** [comment]
I don't think such feature will be in any use for many players. 

What I can suggest you to do is write your own bot, where if it notices that the game has "now playing" song in the txt file to auto deafen you, and when its empty to undeafen. 
You can find that file in `QUAVER_DIRECTORY\Data\Temp\Now Playing`

**Comment by EpiCreeper** [comment]
geometry dash is not a rhythm game. sorry, i was angry and had to get that out of the way.

this feature could be really great and is something ive been wanting in the game for a while actually, ever since i heard of that option in megahack. it could probably be done with a plugin but i can see this being in the game as a qol option. i think it could work in quaver, it just needs to be a little more involved.

the way id implement something like this, id have both percent selection and an accuracy. the game would defen after the precent portion of the map is reached as long as a certain accuracy is maintained. there should probably bee a short cooldown so the button wont be continuedly pressed when close to a certain acc.
if you want it to be real fancy you can add options to use time instead of percents and combo/life instead of accuracy, but i think acc works well for most

**Comment by dannws** [comment]
my bad, didnt mean to offend you!

**Comment by AiAe** [comment]
I really don't see this being good QoL even more when we cannot control your Discord, other than maybe sending a key press that u define to mute/unmute. 
Here is a basic auto hot key script that will do the same thing
https://chatgpt.com/share/671b9b63-5f14-8005-8a55-27186113bfc0
