### ISSUE TITLE
Make BPM changes not affect SV

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#631]
My proposal from Discord: make it so BPM changes do not affect SV, only explicit SV changes affect SV.
Pros:
- no need to check common bpm and normalize SV;
- nothing breaks if u add bpm changes;
- all SV changes make sense;

Cons:
- need to manually slow down on low bpm if you're into that;
- might be issues with o!m maps but should be convertible (for each BPM change emit both BPM and SV).

**Comment by staravia** [comment]
We could add a toggle for this

**Comment by YaLTeR** [comment]
No we should just make this the default with a qua version bump. Common BPM is dumb

**Comment by percyqaz** [comment]
I agree with YaLTeR - BPM affected scrolling in osu is a relic from when scroll speed was tied to a scale of BPM. When this was changed, fixed scroll speed had to change when BPM changed to match proportions in scaled speed or fixed users would get an advantage.

It makes sense for SV points and BPM changes to be totally independent since osu's behaviour is an inconvenience 99 times out of 100 and when converting from o!m, both an SV and BPM point can be placed.
