### ISSUE TITLE
Customize game when first time playing it

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#738]
1. Have option to pick skin with preview (image?)
2. Change skin.ini settings like:
 - Draw slider ends
 - Split key fields with border
 - ~~Colors~~
3. Have option to try it before saving
4. Run Calibrate Offset after or with option 3

**Comment by Janko5** [comment]
I don't know if setting the offset at the very beginning, when the player has no sense of rythm yet, makes sense. First, beginner player should play some time to feel the rhythm and then try to set an offset matching him. Instead, choosing scroll option would be better

**Comment by YaLTeR** [comment]
That's pretty cool. Offset calibrator on fist launch would still be helpful for experienced players.

**Comment by Fretzi** [comment]
I think Janko has a point there, and I got two different ideas how we could handle it instead.
First, simply add the addition "If you do not know what this means, skip it", as most newbies don't know about offset anyway.
Or second, which is the option I prefer; add an additional question about wether the person has played a rhythm game before, and change the setup screen based on the choice.
Newbies can then skip over the offset setup, and on another note we can use the future tutorial map there without enforcing it on players who are not new to this type of game.

So on the first launch, the client would show you:
"Hello, welcome to Quaver. Is this your first time playing a rhythm game?" >YesNo1
"Would you like to set up the game first?" >YesNo2
  `If YesNo2=No` -> Go to main menu, otherwise start set up
Now allow to choose the skin options like draw slider ends, key fields splitting, as they are useful for both new and experienced players, given we are going to add a preview for every option.
  `If YesNo1=No` -> add an offset calibrator at the end and skip the tutorial map
    `If YesNo1=Yes` -> Skip offset calibrator and add the tutorial map after the set up

What do you think about perhaps enforcing the set up when choosing you are new?
Or even about this whole idea in general?
I would like to hear some opinions regarding this idea.
