### ISSUE TITLE
Add Visual Delay Adjustment

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#855]
Visual delay is helpful in a lot of ways. I've seen the phenomenon, that too many people quit Etterna, because it _"doesn't feel right"_ as they transitioned from osu!, too many times now. I've wondered why that is when I tried out Etterna, because I had the same issue as well and I came to following conclusion.

It should be known, that Etterna has less visual lag than osu!, as it is more optimised for VSRG. Thus people, who are accustomed to osu!'s visual delay won't have the same feeling when playing Etterna. People who play with the exact same skin/hitpos/(translated) scroll speed/etc. will always hit early by about 15-25ms. Same issue with Quaver. 

I've counteracted that in Etterna by setting my visual delay to about 0.020s (20ms) and have had no problems with it feeling weird/off in any way. I've had people, who complained about the same issue, try that trick as well and they also felt like it fixed the issue. They used the same value (0.020s), so I will simply assume that that is the amount of difference in visual delay between osu! and Etterna. Not sure what it will be exactly in Quaver, but that's for trial and error.

My proposed solution would be to add a slider, which will add visual delay ranging from -100ms to +100ms. Maybe add a button to apply the visual delay only during gameplay. There's no disadvantage with implementing the _optional_ visual delay, as it won't affect players, who are already accustomed to Quaver and won't really affect anyone other than those who want it. 

There's a lot of things I tried in Quaver, because it felt off the same way Etterna did. I changed my scroll speed, used a top lane cover, adjusted my offset, played around with Hit Position. Still felt off. 

Final Conclusion:
\+ Optional feature, which will help those who need it
\+ More customizability is always good.
\- No disadvantages.

**Comment by YaLTeR** [comment]
I actually have a use case for visual delay myself, I currently have to play on a laptop and there's some lag or delay somewhere which makes the game look off. Right now I figured out a way to compensate for it by moving my hit position to below the top of the receptors (equivalent to negative visual delay), but it'd be nice if this was an actual setting.

The main issue is that with negative visual delay the notes would have to fall below the receptors (same as adjusting the hit position) because you cannot tell if the player will hit them on time or not (the hit hasn't happened yet). For positive visual delay we can do better than hit position adjustment though since we can align the hits properly.

Another issue with visual delay is that ideally it should vary with scroll speed changes (lower scroll speed needs less absolute visual delay), but I'm not sure that's a good / fair idea to implement (and if it'll even work properly).
