### ISSUE TITLE
Lower resolution

### ISSUE THREAD

**Issue by Pipperchu** [Quaver/Quaver#880]
**Is your feature request related to a problem? Please describe.**
When trying to do a resolution lower than 800x600, the game automatically re-sets it to 800x600 because that's the lowest it can go.
**Describe the solution you'd like**
To be able to edit the cfg file to put any resolution the player wants.
**Describe alternatives you've considered**

**Additional context**

**Comment by itzinferr** [comment]
Actually I'd like to see this happening as I use a secondary CRT monitor for fast-paced games that supports 130hz at a 640x512 resolution and I can't play on that monitor due to this, not only such a low resolution isn't accepted but also the aspect ratio doesn't work properly with the game as for now.
