### ISSUE TITLE
Buttons not working properly

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#916]
**Describe the bug**
You can't click the button where the button is, need to go bit right and down (not all buttons, for example main menu music buttons, next, stop etc OR modifiers speed buttons, left and right)

**To Reproduce**
Click the buttons said above

**Desktop (please complete the following information):**
- W10
- Might be because 2 monitor setup? not sure

Video
https://www.youtube.com/watch?v=zT8XQ476eao

**Comment by KcHecKa** [comment]
This is because you're using a circle, osu! style, cursor. If you take a look at the default cursor, it's like a mouse cursor, and you only click on things with the very tip of the mouse cursor and not the middle of it. Perhaps there could be a setting for circle cursors to be clickable everywhere, or to just have cursors in general work this way.

**Comment by Swan** [comment]
`CenterCursor = True` in skin.ini will fix this.
