### ISSUE TITLE
sh: /home/username/.steam/root/steam.sh: No such file or directory

### ISSUE THREAD

**Issue by nobbele** [Quaver/Quaver#942]
**Describe the bug**
When running quaver.sh it gives `sh: /home/username/.steam/root/steam.sh: No such file or directory`

**To Reproduce**
1. Download Quaver
2. Run quaver.sh

**Expected behavior**
Quaver runs

**Desktop (please complete the following information):**
 - OS: Manjaro

Installed Steam using flatpak

**Comment by YaLTeR** [comment]
Flatpaked Steam runs in a container, so even adjusting the path to `steam.sh` wouldn't straight-forwardly work. I tried to run development Quaver under flatpak Steam briefly but it turned out to be non-trivial, which is, I imagine, not a Quaver-specific issue, but rather a general running-development-builds-under-flatpak-Steam issue. I suggest installing Steam in a regular fashion to run development Quaver.

That said, regular Steam-installed Quaver didn't run under the flatpak Steam either, I would blame libgdiplus.so or libdl.so, and I would wait until we get rid of libgdiplus before testing Quaver under flatpak Steam again.
